2.20 Numpy

In [1]:
import numpy as np
o_10 = np.array ([2,4,6,8,10,12])
print(o_10)
print("================================")
c_10 = np.array([[4,5,6,7,],[8,7,6,5]])
print(c_10)
print("================================")
a_10 = np.array([[[1,3,6,9],[12,15,18,21]],
                 [[24,27,24,21],[18,15,12,9]],
                 [[3,6,9,12],[15,18,21,24]]])
print(a_10)
print("================================")

[ 2  4  6  8 10 12]
[[4 5 6 7]
 [8 7 6 5]]
[[[ 1  3  6  9]
  [12 15 18 21]]

 [[24 27 24 21]
  [18 15 12  9]]

 [[ 3  6  9 12]
  [15 18 21 24]]]


In [2]:
o_10.ndim

1

In [3]:
o_10.shape

(6,)

In [4]:
c_10.ndim

2

In [5]:
c_10.shape

(2, 4)

In [6]:
a_10.ndim

3

In [7]:
a_10.shape

(3, 2, 4)

In [8]:
r_10 = np.array([[4,8,12,16],[20,24,28,32],[36,40,44,48]])
print(r_10)

[[ 4  8 12 16]
 [20 24 28 32]
 [36 40 44 48]]


In [9]:
r_10[0,2]

12

In [10]:
r_10[1,:]

array([20, 24, 28, 32])

In [11]:
r_10[:,2]

array([12, 28, 44])

In [12]:
r_10[0,1:3]

array([ 8, 12])

In [13]:
r_10[0,0:2:2]

array([4])

In [14]:
r_10[1,1]=90
print(r_10)

[[ 4  8 12 16]
 [20 90 28 32]
 [36 40 44 48]]


In [15]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.ones((2,4,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [19]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [20]:
np.random.rand(4,3)

array([[0.01114334, 0.50324993, 0.9574065 ],
       [0.82986444, 0.96101427, 0.20200935],
       [0.09294925, 0.94664249, 0.20734541],
       [0.94451615, 0.55443691, 0.42786375]])

In [21]:
np.random.randint(1,10,size=(4,4))

array([[1, 7, 5, 3],
       [3, 7, 3, 3],
       [7, 6, 7, 8],
       [2, 5, 4, 3]])

In [22]:
r_10 = np.zeros((10,10))
print(r_10)
print("=================================")
o_10 = np.identity(10)
print(o_10)
print("=================================")
s_10 = 9*o_10
print(s_10)
print("=================================")
a_10 = np.ones((8,8))
n_10 = np.identity(8)*8
i_10 = n_10 + a_10
print(i_10)
print("=================================")
s_10[1:-1,1:-1]
print(s_10)
print("=================================")
t_10 = np.identity(6)*9
s_10[2:-2,2:-2] = t_10
print(s_10)
print("=================================")
h_10 = np.ones((4,4))*2
j_10 = np.identity(4)*7
k_10 = h_10 + j_10
print(k_10)
print("=================================")
s_10[3:-3,3:-3] = k_10
print(k_10)
print("=================================")



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]
[[9. 1.

In [23]:
#base matriks
r_10 = np.zeros((10,10))
print(r_10)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
#diagonal utama
o_10 = np.identity(10)
print(o_10)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [28]:
#diagonal angka 8
s_10 = 8*o_10
print(s_10)

[[8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 8.]]


In [30]:
#menginisialisasi array t
t_10 = np.array([2,3,5,7,11])
print(t_10)

[ 2  3  5  7 11]


In [31]:
 #array s sama dengan t
s_10 = t_10
print(s_10)

[ 2  3  5  7 11]


In [32]:
s_10[0] = 100
print(s_10)

[100   3   5   7  11]


In [33]:
x_10 = np.array([2,3,5,7,11])
print(x_10)

[ 2  3  5  7 11]


In [35]:
y_10 = x_10.copy()
print(y_10)
print()
y_10[0] = 84
print(y_10)
print()
print(x_10)

[ 2  3  5  7 11]

[84  3  5  7 11]

[ 2  3  5  7 11]


In [36]:
z_10 = np.array([16,18,20,22,24])
print(z_10)

a_10 = z_10.copy()
print(a_10)

a_10[0] = 6
print(a_10)

print(z_10)

[16 18 20 22 24]
[16 18 20 22 24]
[ 6 18 20 22 24]
[16 18 20 22 24]


In [39]:

print('Beberapa operasi matematika pada numpy di matriks :')
k_10 = np.array([12,14,16,18,20,22,24,26,28])
print(k_10)


print('Berikut ini hasil dari penjumlahan matriks d ditambah 2: ')
print(k_10+3)

print('Berikut ini hasil dari pengurangan matriks d dikurang 2: ')
print(k_10-3)

print('Berikut ini hasil dari perkalian matriks d dikali 2: ')
print(k_10*3)

print('Berikut ini hasil dari pembagian matriks d dibagi 2: ')
print(k_10/3)

print('Berikut ini hasil dari matriks d dipangkatkan 2: ')
print(k_10**3)

Beberapa operasi matematika pada numpy di matriks :
[12 14 16 18 20 22 24 26 28]
Berikut ini hasil dari penjumlahan matriks d ditambah 2: 
[15 17 19 21 23 25 27 29 31]
Berikut ini hasil dari pengurangan matriks d dikurang 2: 
[ 9 11 13 15 17 19 21 23 25]
Berikut ini hasil dari perkalian matriks d dikali 2: 
[36 42 48 54 60 66 72 78 84]
Berikut ini hasil dari pembagian matriks d dibagi 2: 
[4.         4.66666667 5.33333333 6.         6.66666667 7.33333333
 8.         8.66666667 9.33333333]
Berikut ini hasil dari matriks d dipangkatkan 2: 
[ 1728  2744  4096  5832  8000 10648 13824 17576 21952]


In [41]:
print('matriks yang akan dioperasikan :')
print('l')
l_10 = np.array([[4,5,6,7],[8,9,10,11]])
print(l_10)
print('===================================================')
print('k')
k_10 = np.array([[12,13],[14,15],[16,17],[18,19]])
print(k_10)
print('===================================================')
print('hasil operasi perkalian matriks l dan k adalah:')
m_10 = np.matmul(l_10,k_10)
print(m_10)

matriks yang akan dioperasikan :
l
[[ 4  5  6  7]
 [ 8  9 10 11]]
k
[[12 13]
 [14 15]
 [16 17]
 [18 19]]
hasil operasi perkalian matriks l dan k adalah:
[[340 362]
 [580 618]]


In [44]:
print('matriks c :')
a_10 = np.array([[1,2,4,6],
            [8,10,12,14],
            [16,18,20,22]])
print (a_10)

print('nilai minimum elemen pada matriks a adalah:')
b_10 = np.min(a_10)
print(b_10)

print('nilai minimum elemen baris pada masing-masing baris matriks a adalah:')
c_10 = np.min(a_10, axis=1)
print(c_10)

print('nilai minimum elemen kolom pada masing-masing baris matriks a adalah :')
d_10 = np.min(a_10, axis=0)
print(d_10)

print('nilai maksimum elemen pada matriks a adalah :')
e_10 = np.max(a_10)
print(e_10)

print('nilai maksimum elemen baris pada masing-masing baris matriks a adalah :')
f_10 = np.max(a_10, axis=1)
print(f_10)

print('nilai maksimum elemen kolom pada masing-masing baris matriks a adalah  :')
i_10 = np.max(a_10, axis=0)
print(i_10)

print('jumlah nilai semua elemen pada matriks a adalah :')
j_10 = np.sum(a_10)
print(j_10)

print('jumlah nilai elemen pada masing-masing kolom matriks a adalah :')
j_10=np.sum(a_10,axis=0)
print(j_10)

print('jumlah nilai elemen pada masing-masing baris matriks a adalah :')
k_10 = np.sum(a_10,axis=1)
print(k_10)

matriks c :
[[ 1  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
nilai minimum elemen pada matriks a adalah:
1
nilai minimum elemen baris pada masing-masing baris matriks a adalah:
[ 1  8 16]
nilai minimum elemen kolom pada masing-masing baris matriks a adalah :
[1 2 4 6]
nilai maksimum elemen pada matriks a adalah :
22
nilai maksimum elemen baris pada masing-masing baris matriks a adalah :
[ 6 14 22]
nilai maksimum elemen kolom pada masing-masing baris matriks a adalah  :
[16 18 20 22]
jumlah nilai semua elemen pada matriks a adalah :
133
jumlah nilai elemen pada masing-masing kolom matriks a adalah :
[25 30 36 42]
jumlah nilai elemen pada masing-masing baris matriks a adalah :
[13 44 76]
